# Site Settings
title:               A Crack in the Code
tagline:             Musings on Coding and Life
description:
url:                http://www.chadkreutzer.com
baseurl:            /crack-in-the-code
author:
  name:              "Chad Kreutzer"
  email:             "chadkreutzer@outlook.com"
  twitter:           "kanthalion"
  instagram:         "chadkreutzer"
  github:            "ChadKreutzer"
  facebook:          "chad.kreutzer"
  linkedin:          "chad-kreutzer-888a9b29"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              crack-in-the-code

# Build settings
markdown:            rdiscount
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
